Update main.py
advanced-security/set-codeql-language-matrix pull request #3
Opened 2023-03-28 18:42 UTC by CallMeGreg

Added support for typescript & kotlin, updated some print statements

2023-04-06 15:11 UTC, leftrightleft requested changes

2023-04-12 00:20 UTC, leftrightleft commented on main.py
> +    # print("{0}={1}".format(output_name, value))
Friendly bump @CallMeGreg

2023-04-12 13:25 UTC, CallMeGreg commented on main.py
> +    # print("{0}={1}".format(output_name, value))
@leftrightleft hey sorry for leaving you hanging! I removed the commented out line, so we should be all set

2023-04-13 17:17 UTC, leftrightleft approved these changes

2023-04-13 17:19 UTC, merged